apiVersion: v1
kind: Service
metadata:
  labels:
    app: openclaw
  name: openclaw
spec:
  ports:
    - port: 18789
      targetPort: gateway
      protocol: TCP
      name: gateway
    - port: 18793
      targetPort: canvas
      protocol: TCP
      name: canvas
  selector:
    app: openclaw
  type: ClusterIP
